apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mycertificat
  namespace: traefik
spec:
  dnsNames:
    - "*.fayit.org"
  secretName: traefik
  issuerRef:
    name: letsencrypt-clusterissuer
    kind: ClusterIssuer