apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer
  namespace: cert-manager
spec:
  acme:
    email: zouaoui.faycal.p@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - selector:
            dnsZones:
              - "fayit.org" #My domain 
      dns01:
        route53:
          region: eu-west-1
          accessKeyID: AKI**************  # Access Key of the user with dns Rights to do a DNS Challenge 
          hostedZoneID: Z0**************
          secretAccessKeySecretRef:
            name: secret-key  # Secret Key of the user with dns Rights to do a DNS Challenge , Strored in this secret 
            key: cert-manager-secret-key
