apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mykubernetes
  region: eu-west-1
  version: "1.17"

vpc:
  subnets:
    private:
      eu-north-1a: { id: subnet-07f8ae59903ed1800 }
      eu-north-1b: { id: subnet-0462586bfe62b1281 }
      eu-north-1c: { id: subnet-0ed982c259aa2cfc7 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.medium
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        certManager: true
        albIngress: true
    ssh:
      allow: true  
