apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mykubernetes
  region: eu-west-1

vpc:
  subnets:
    private:
      eu-north-1a: { id: subnet-02d5645d2f00d3ae4 }
      eu-north-1b: { id: subnet-05e909d3576184dd3 }
      eu-north-1c: { id: subnet-001d822e295350c67 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.medium
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        certManager: true
        albIngress: true
    ssh:
      allow: true  
